config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'messages/index'
  root to: "messages#index"
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    current_user.update(user_params)
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
　　<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      hogefuga
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <a href="#">チャットを終了する</a>
    </div>
  </div>
</div>

<div class="messages">
<div class="message">
    <div class="upper-message">
      <div class="message-user">
        Tom
      </div>
      <div class="message-date">
        2020/3/31(Wed) 12:43:30
      </div>
    </div>
    <div class="lower-message">
      <div class="message-content">
        おはよう
      </div>
    </div>
  </div>

  <div class="message">
    <div class="upper-message">
      <div class="message-user">
        Tom
      </div>
      <div class="message-date">
        2020/3/31(Wed) 12:47:30
      </div>
    </div>
    <div class="lower-message">
      <div class="message-content">
        こんばんは
      </div>
    </div>
  </div>


</div>

<div class="form">
<div class="form-input">
    <input class="form-message" placeholder= "type a message">
    <label class="form-image">
      <span class="image-file">画像</span>
      <input type="file" class="hidden">
    </label>
  </div>
  <input class="form-submit" type="submit" value="送信">
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
   <%= link_to current_user.name, edit_user_path(current_user) %>
    <a href="#">Tom</a>
  </div>
  <div class="create-room">
    <a href="#">チャットを作成する</a>
  </div>
</div>

<div class="rooms">
<div class="room">
    <div class="room-name">
      <a href="#">techroom1</a>
    </div>
  </div>
  <div class="room">
    <div class="room-name">
      <a href="#">techroom2</a>
    </div>
  </div>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>